### PR TITLE
updated UA script with respective GA script

### PR DESCRIPTION
**Pull request by rajiqxf2**
Updated with script & tested UI on localhost

### CODE REVIEW

**Comment by PreedhiVivek** [comment]
@rajiqxf2 ,
Were you able to verify traffic via the real-time report when you ran the app locally with your code change?
I did not run your code change locally. However looking at it,
The analytics.js tracking code in the footer is replaced with gtag.  But it has to be replaced with the gtag code in the header. 
gtag should always be placed right under `<head>` as mentioned in the "Instructions to install gtag tracking code manually" on Google Analytics.

**Comment by rajiqxf2** [comment]
> @rajiqxf2 , Were you able to verify traffic via the real-time report when you ran the app locally with your code change? I did not run your code change locally. However looking at it, The analytics.js tracking code in the footer is replaced with gtag. But it has to be replaced with the gtag code in the header. gtag should always be placed right under `<head>` as mentioned in the "Instructions to install gtag tracking code manually" on Google Analytics.

@PreedhiVivek  
1. I replaced the code where it is being used to collect the analytics currently.
2. Sorry I am not able to understand, how can we collect real-time analytics without deploying the GA4 code on the live server 
3. I think it does not matter header or footer as long as that footer reflects in all the pages where all we want to collect the analytics
4. I could test only if all the web pages with header and footer are up on local after updating the code.

**Comment by qxf2** [comment]
> 2\. Sorry I am not able to understand, how can we collect real-time analytics without deploying the GA4 code on the live server

@rajiqxf2 - data from localhost also goes to Google Analytics. So run the app (with your new code) locally and then go to GA on the web browser. Check if you see real time data and from your city. Vary the pages to see if that reports.

**Comment by rajiqxf2** [comment]
> > 2. Sorry I am not able to understand, how can we collect real-time analytics without deploying the GA4 code on the live server
> 
> @rajiqxf2 - data from localhost also goes to Google Analytics. So run the app (with your new code) locally and then go to GA on the web browser. Check if you see real time data and from your city. Vary the pages to see if that reports.



> > 2. Sorry I am not able to understand, how can we collect real-time analytics without deploying the GA4 code on the live server
> 
> @rajiqxf2 - data from localhost also goes to Google Analytics. So run the app (with your new code) locally and then go to GA on the web browser. Check if you see real time data and from your city. Vary the pages to see if that reports.

 I see localhost IP traffic is being generated for my location as of yesterday 
 
image

image

**Pull request merged**
